# https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 800

[gcloud]
disabled = true

[git_branch]
truncation_length = 30

[kubernetes]
disabled = false
