# https://starship.rs/config/
"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 800

[gcloud]
disabled = true

[git_branch]
truncation_length = 30
symbol = " "

[kubernetes]
disabled = false
format = '[$symbol $namespace]($style) in '
symbol = "⎈ "
style = "33 bold"

[kubernetes.context_aliases]
"staging" = "stag."
"production" = "prod."
"sandbox" = "sand."

[nodejs]
symbol = " "

[package]
symbol = " "
