#! /bin/zsh

base=$(git base)

git ff "$base"
if [ "$base" = master ]; then
	git merge master
else
	git rb
fi

if [ $? -ne 0 ]; then
	return $?
fi

local new_base="$1"

if [ ! -z "$new_base" ]; then
	git ff "$new_base"
	git base "$new_base"
	git rb
fi
